# Stage 1: Build
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

# Copy entire project (pom.xml is here)
COPY . .

# Build the jar
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Copy built jar from build stage
COPY --from=build /app/target/durga-puja-backend.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]